// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXv1APr_XGteur1PSFcuuhMIZS4ExqHuY',
    appId: '1:372023001972:web:da4fb5e2538520b125e221',
    messagingSenderId: '372023001972',
    projectId: 'kelas-belajar-87d24',
    authDomain: 'kelas-belajar-87d24.firebaseapp.com',
    storageBucket: 'kelas-belajar-87d24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2sRMDUxigTvoVMKj-TbJiaB1GfLB9_o',
    appId: '1:372023001972:android:e4a31c823827810f25e221',
    messagingSenderId: '372023001972',
    projectId: 'kelas-belajar-87d24',
    storageBucket: 'kelas-belajar-87d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJsQgzVQgjUVBHPhkMqVVmg_0LTssUxg',
    appId: '1:372023001972:ios:e19247d2f6f9188d25e221',
    messagingSenderId: '372023001972',
    projectId: 'kelas-belajar-87d24',
    storageBucket: 'kelas-belajar-87d24.appspot.com',
    iosBundleId: 'com.edjavu.kelasBelajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJsQgzVQgjUVBHPhkMqVVmg_0LTssUxg',
    appId: '1:372023001972:ios:e19247d2f6f9188d25e221',
    messagingSenderId: '372023001972',
    projectId: 'kelas-belajar-87d24',
    storageBucket: 'kelas-belajar-87d24.appspot.com',
    iosBundleId: 'com.edjavu.kelasBelajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXv1APr_XGteur1PSFcuuhMIZS4ExqHuY',
    appId: '1:372023001972:web:61ec777ad1cdc5c525e221',
    messagingSenderId: '372023001972',
    projectId: 'kelas-belajar-87d24',
    authDomain: 'kelas-belajar-87d24.firebaseapp.com',
    storageBucket: 'kelas-belajar-87d24.appspot.com',
  );
}
